Практическая работа №5 - Анализ датасета

Цель: Реализовать базовый анализ датасета, включающий вывод всех уникальных значений, сортировку по определенным параметрам, удаление ненужных столбцов и строк, замену определенных значений, удаление дубликатов, проведение анализа с использованием функций info и describe, выборку данных по строкам и столбцам с помощью loc, а также сохранение нового датасета.

Описание датасета Terraria: NAME - НАЗВАНИЕ ПРЕДМЕТОВ, CLASS - КЛАСС ПЕРСОНАЖА, GAME PROGRESSION - ПРОГРЕСС ИГРЫ, DPS (SINGLE TARGET) - УРОР ПО ОДИНОЧНОЙ ЦЕЛИ, DPS (MULTI TARGET) - УРОН ПО МНОГОЦЕЛЕВОЙ, DPS (SINGLE TARGET + PROYECTILE ONLY) - УРОН ТОЛЬКО ОДИНОЧНОЙ ЦЕЛИ + СНАРЯД, DPS (MULTI TARGET + PROYECTILE ONLY) - УРОН ТОЛЬКО ДЛЯ НЕСКОЛЬКИХ ЦЕЛЕЙ + СНАРЯД, OBSERVATIONS - НАБЛЮДЕНИЕ

In [36]:
import pandas as pd
import numpy as np
Terraria = pd.read_csv("Terraria.csv")
Terraria

,NAME,CLASS,GAME PROGRESSION,DPS (SINGLE TARGET),DPS (MULTI TARGET),DPS (SINGLE TARGET + PROYECTILE ONLY),DPS (MULTI TARGET + PROYECTILE ONLY),OBSERVATIONS
0,Zenith,Melee,Post-Moonlord,4800,13000.0,NaN,NaN,NaN
1,Last Prism,Mage,Post-Moonlord,3657,1142.0,NaN,NaN,Fully charged
2,Star Wrath,Melee,Post-Moonlord,2700,5800.0,1500.0,3700.0,NaN
3,Terrarian,Melee,Post-Moonlord,2200,4600.0,700.0,1000.0,NaN
4,Meowmere,Melee,Post-Moonlord,2100,6400.0,1300.0,3400.0,NaN
...,...,...,...,...,...,...,...,...
390,Paper Plane,Ranger,Pre-Boss,14,NaN,NaN,NaN,Does not pierce
391,Finch Staff,Summoner,Pre-Boss,10,25.0,NaN,NaN,NaN
392,Flameburst Rod,Summoner,Pre-Boss,8,18.0,NaN,NaN,Only two dummies
393,Flinx Staff,Summoner,Pre-Boss,8,70.0,NaN,NaN,NaN
394,Lightning Aura Rod,Summoner,Pre-Boss,8,24.0,NaN,NaN,NaN

Этап 2: После этого требуется вывести данные с использованием команды вашдатасет.head().

In [38]:
Terraria.head()

,NAME,CLASS,GAME PROGRESSION,DPS (SINGLE TARGET),DPS (MULTI TARGET),DPS (SINGLE TARGET + PROYECTILE ONLY),DPS (MULTI TARGET + PROYECTILE ONLY),OBSERVATIONS
0,Zenith,Melee,Post-Moonlord,4800,13000.0,NaN,NaN,NaN
1,Last Prism,Mage,Post-Moonlord,3657,1142.0,NaN,NaN,Fully charged
2,Star Wrath,Melee,Post-Moonlord,2700,5800.0,1500.0,3700.0,NaN
3,Terrarian,Melee,Post-Moonlord,2200,4600.0,700.0,1000.0,NaN
4,Meowmere,Melee,Post-Moonlord,2100,6400.0,1300.0,3400.0,NaN

Этап 3: Затем необходимо отобразить размерность массива, используя вашдатасет.shape.

In [39]:
Terraria.shape

(395, 8)

Этап 4: Далее требуется вывести наименование всех колонок, написать что они означают в нашем датасете с помощью .columns

In [40]:
Terraria.columns

Index(['NAME', 'CLASS', 'GAME PROGRESSION', 'DPS (SINGLE TARGET)',
       'DPS (MULTI TARGET)', 'DPS (SINGLE TARGET + PROYECTILE ONLY)',
       'DPS (MULTI TARGET + PROYECTILE ONLY)', 'OBSERVATIONS'],
      dtype='object')

Этап 5: Затем необходимо вывести все уникальные значения с помощью .unique

In [41]:
Terraria['CLASS'].unique()

array(['Melee', 'Mage', 'Ranger', 'Summoner'], dtype=object)

Этап 6: Далле нужно сделать сортировку по определенным параметрам с помощью .sort_values

In [42]:
Terraria.sort_values(by='DPS (SINGLE TARGET)')

,NAME,CLASS,GAME PROGRESSION,DPS (SINGLE TARGET),DPS (MULTI TARGET),DPS (SINGLE TARGET + PROYECTILE ONLY),DPS (MULTI TARGET + PROYECTILE ONLY),OBSERVATIONS
394,Lightning Aura Rod,Summoner,Pre-Boss,8,24.0,NaN,NaN,NaN
393,Flinx Staff,Summoner,Pre-Boss,8,70.0,NaN,NaN,NaN
392,Flameburst Rod,Summoner,Pre-Boss,8,18.0,NaN,NaN,Only two dummies
391,Finch Staff,Summoner,Pre-Boss,10,25.0,NaN,NaN,NaN
390,Paper Plane,Ranger,Pre-Boss,14,NaN,NaN,NaN,Does not pierce
...,...,...,...,...,...,...,...,...
4,Meowmere,Melee,Post-Moonlord,2100,6400.0,1300.0,3400.0,NaN
3,Terrarian,Melee,Post-Moonlord,2200,4600.0,700.0,1000.0,NaN
2,Star Wrath,Melee,Post-Moonlord,2700,5800.0,1500.0,3700.0,NaN
1,Last Prism,Mage,Post-Moonlord,3657,1142.0,NaN,NaN,Fully charged
0,Zenith,Melee,Post-Moonlord,4800,13000.0,NaN,NaN,NaN

Этап 7: Затем необходимо выполнить удаление ненужных столбцов или строк с помощью .drop

In [43]:
Terraria.drop(columns = ["OBSERVATIONS"], inplace=True)

Этап 8: Далее нужно заменить определенные значения в датасете (например, пустые) с помошью .replace

In [44]:
Terraria["GAME PROGRESSION"] = Terraria["GAME PROGRESSION"].replace(Terraria["GAME PROGRESSION"].unique(), "Unknown")
Terraria

,NAME,CLASS,GAME PROGRESSION,DPS (SINGLE TARGET),DPS (MULTI TARGET),DPS (SINGLE TARGET + PROYECTILE ONLY),DPS (MULTI TARGET + PROYECTILE ONLY)
0,Zenith,Melee,Unknown,4800,13000.0,NaN,NaN
1,Last Prism,Mage,Unknown,3657,1142.0,NaN,NaN
2,Star Wrath,Melee,Unknown,2700,5800.0,1500.0,3700.0
3,Terrarian,Melee,Unknown,2200,4600.0,700.0,1000.0
4,Meowmere,Melee,Unknown,2100,6400.0,1300.0,3400.0
...,...,...,...,...,...,...,...
390,Paper Plane,Ranger,Unknown,14,NaN,NaN,NaN
391,Finch Staff,Summoner,Unknown,10,25.0,NaN,NaN
392,Flameburst Rod,Summoner,Unknown,8,18.0,NaN,NaN
393,Flinx Staff,Summoner,Unknown,8,70.0,NaN,NaN
394,Lightning Aura Rod,Summoner,Unknown,8,24.0,NaN,NaN

Этап 9: Затем необходимо выполнить удаление дубликатов с помощью .drop_duplicates()

In [46]:
Terraria = Terraria.drop_duplicates()
Terraria

,NAME,CLASS,GAME PROGRESSION,DPS (SINGLE TARGET),DPS (MULTI TARGET),DPS (SINGLE TARGET + PROYECTILE ONLY),DPS (MULTI TARGET + PROYECTILE ONLY)
0,Zenith,Melee,Unknown,4800,13000.0,NaN,NaN
1,Last Prism,Mage,Unknown,3657,1142.0,NaN,NaN
2,Star Wrath,Melee,Unknown,2700,5800.0,1500.0,3700.0
3,Terrarian,Melee,Unknown,2200,4600.0,700.0,1000.0
4,Meowmere,Melee,Unknown,2100,6400.0,1300.0,3400.0
...,...,...,...,...,...,...,...
390,Paper Plane,Ranger,Unknown,14,NaN,NaN,NaN
391,Finch Staff,Summoner,Unknown,10,25.0,NaN,NaN
392,Flameburst Rod,Summoner,Unknown,8,18.0,NaN,NaN
393,Flinx Staff,Summoner,Unknown,8,70.0,NaN,NaN
394,Lightning Aura Rod,Summoner,Unknown,8,24.0,NaN,NaN

Этап 10: Далее нужно провести анализ с помощью функций .describe()

In [18]:
Terraria.describe()

,DPS (SINGLE TARGET),DPS (MULTI TARGET),DPS (SINGLE TARGET + PROYECTILE ONLY),DPS (MULTI TARGET + PROYECTILE ONLY)
count,395.000000,309.000000,25.000000,19.000000
mean,262.273418,651.543689,348.600000,961.315789
std,437.778258,1102.016874,380.502738,1036.653057
min,8.000000,17.000000,30.000000,75.000000
25%,58.000000,150.000000,80.000000,250.000000
50%,130.000000,350.000000,250.000000,650.000000
75%,289.000000,771.000000,500.000000,1050.000000
max,4800.000000,13000.000000,1500.000000,3700.000000

Этап 11: Затем необходимо Провести выборку данных по строкам и столбцам с помощью .loc

In [20]:
subset = Terraria.loc[[0, 1, 2], ['NAME', 'CLASS']]
subset

         NAME  CLASS
0      Zenith  Melee
1  Last Prism   Mage
2  Star Wrath  Melee

Этап 12: Далее нужно Провести анализ с помощью функций .info()

In [21]:
Terraria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 8 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   NAME                                   395 non-null    object
 1   CLASS                                  395 non-null    object
 2   GAME PROGRESSION                       395 non-null    object
 3   DPS (SINGLE TARGET)                    395 non-null    int64
 4   DPS (MULTI TARGET)                     309 non-null    float64
 5   DPS (SINGLE TARGET + PROYECTILE ONLY)  25 non-null     float64
 6   DPS (MULTI TARGET + PROYECTILE ONLY)   19 non-null     float64
 7   OBSERVATIONS                           395 non-null    object
dtypes: float64(3), int64(1), object(4)
memory usage: 24.8+ KB

Финальный этап: Необходимо сохранить наш датасет с помощью .to_csv и написать в конце нужный индекс. Если он False то не будет сохранен, а если True то он сохраниться

In [33]:
Terraria.to_csv("Terraria_clear.csv", index=True)
Terraria

,NAME,CLASS,GAME PROGRESSION,DPS (SINGLE TARGET),DPS (MULTI TARGET),DPS (SINGLE TARGET + PROYECTILE ONLY),DPS (MULTI TARGET + PROYECTILE ONLY)
0,Zenith,Melee,Unknown,4800,13000.0,NaN,NaN
1,Last Prism,Mage,Unknown,3657,1142.0,NaN,NaN
2,Star Wrath,Melee,Unknown,2700,5800.0,1500.0,3700.0
3,Terrarian,Melee,Unknown,2200,4600.0,700.0,1000.0
4,Meowmere,Melee,Unknown,2100,6400.0,1300.0,3400.0
...,...,...,...,...,...,...,...
390,Paper Plane,Ranger,Unknown,14,NaN,NaN,NaN
391,Finch Staff,Summoner,Unknown,10,25.0,NaN,NaN
392,Flameburst Rod,Summoner,Unknown,8,18.0,NaN,NaN
393,Flinx Staff,Summoner,Unknown,8,70.0,NaN,NaN
394,Lightning Aura Rod,Summoner,Unknown,8,24.0,NaN,NaN

Вывод: Мы осуществили базовый анализ датасета, включая вывод уникальных значений, сортировку по определенным параметрам, удаление лишних столбцов и строк, замену определенных значений, исключение дубликатов, анализ при помощи функций info и describe, выборку данных через loc по определенным строкам и столбцам, а также сохранение измененного датасета.